spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3308/human-resource}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.open-in-view=false
server.port: 8091
## MULTIPART (MultipartProperties)
# Enable multipart uploads
spring.servlet.multipart.enabled=true
# Threshold after which files are written to disk.
spring.servlet.multipart.file-size-threshold=2KB
# Max file size.
spring.servlet.multipart.max-file-size=200MB
# Max Request Size
spring.servlet.multipart.max-request-size=215MB
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata

# AWS S3 Configuration
aws.accessKeyId=${AWS_ACCESS_KEY_ID:}
aws.secretKey=${AWS_SECRET_ACCESS_KEY:}
aws.region=${AWS_REGION:ap-south-1}
aws.s3.bucketName=${AWS_S3_BUCKET_NAME:hrms-interview-cv}

#TetLocal API
spring.sms.api.url=${SMS_API_URL:https://api.textlocal.in/send/?}
spring.sms.api.key=${SMS_API_KEY:}
spring.sms.api.sender=${SMS_API_SENDER:TCIANS}

status = error   #The level of internal Log4j events that should be logged to the console.
name = PropertiesConfig

filters = threshold

filter.threshold.type = ThresholdFilter
filter.threshold.level = debug

appenders = console

appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

rootLogger.level = debug
rootLogger.appenderRefs = stdout
rootLogger.appenderRef.stdout.ref = STDOUT


spring.jpa.properties.hibernate.jdbc.batch_size=500
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true

# =========================
# HIBERNATE PERFORMANCE
# =========================
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.generate_statistics=false

# =========================
spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=10
spring.task.execution.pool.queue-capacity=500
spring.task.execution.thread-name-prefix=HRMS-ASYNC-

# =========================
# COMPRESSION
# =========================
server.compression.enabled=true
server.compression.mime-types=application/json,text/html,text/xml,text/plain
