
# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.


mail.server.host=${MAIL_SERVER_HOST:smtp.gmail.com}
mail.server.protocol=${MAIL_SERVER_PROTOCOL:smtp}
mail.server.port=${MAIL_SERVER_PORT:465}
mail.server.username=${MAIL_SERVER_USERNAME:}
mail.server.password=${MAIL_SERVER_PASSWORD:}


