smsSigma.text.url=http://www.smssigma.com/API/WebSMS/Http/v1.0a/index.php?
smsSigma.text.username=${SMS_SIGMA_USERNAME:}
smsSigma.text.password=${SMS_SIGMA_PASSWORD:}
smsSigma.text.senderId=${SMS_SIGMA_SENDER_ID:TCTEST}
smsSigma.text.routeId=518
smsSigma.text.reqId=1
smsSigma.text.format={json|text}
smsSigma.text.status=true
